#!/bin/sh

G=/sys/kernel/config/usb_gadget/yuzu

start_gadget() {
	[ -d /sys/kernel/config ] || mount -t configfs none /sys/kernel/config
	[ -d "$G" ] || mkdir -p "$G"

	echo 0x1d6b > "$G/idVendor"
	echo 0x0104 > "$G/idProduct"
	echo 0x0200 > "$G/bcdUSB"
	echo 0x0100 > "$G/bcdDevice"

	mkdir -p "$G/strings/0x409"
	echo "00000001" > "$G/strings/0x409/serialnumber"
	echo "Yuzu" > "$G/strings/0x409/manufacturer"
	echo "Yuzu Pocket" > "$G/strings/0x409/product"

	mkdir -p "$G/configs/c.1/strings/0x409"
	echo "Terminal + network + help" > "$G/configs/c.1/strings/0x409/configuration"
	echo 120 > "$G/configs/c.1/MaxPower"

	mkdir -p "$G/functions/acm.usb0"
	ln -sf "$G/functions/acm.usb0" "$G/configs/c.1/acm.usb0"

	mkdir -p "$G/functions/ecm.usb0"
	echo "02:00:00:00:00:01" > "$G/functions/ecm.usb0/dev_addr"
	echo "02:00:00:00:00:02" > "$G/functions/ecm.usb0/host_addr"
	ln -sf "$G/functions/ecm.usb0" "$G/configs/c.1/ecm.usb0"

	if [ -f /opt/yuzu-pocket/help.img ]; then
		mkdir -p "$G/functions/mass_storage.usb0"
		echo 1 > "$G/functions/mass_storage.usb0/lun.0/ro"
		echo 1 > "$G/functions/mass_storage.usb0/lun.0/removable"
		echo /opt/yuzu-pocket/help.img > "$G/functions/mass_storage.usb0/lun.0/file"
		ln -sf "$G/functions/mass_storage.usb0" "$G/configs/c.1/mass_storage.usb0"
	fi

	udc="$(ls /sys/class/udc 2>/dev/null | head -n 1 || true)"
	[ -n "$udc" ] && echo "$udc" > "$G/UDC"
	ifconfig usb0 10.0.0.1 netmask 255.255.255.0 up 2>/dev/null || true
}

stop_gadget() {
	[ -d "$G" ] || return 0
	echo "" > "$G/UDC" 2>/dev/null || true
	rm -f "$G/configs/c.1/acm.usb0" "$G/configs/c.1/ecm.usb0" "$G/configs/c.1/mass_storage.usb0"
	rmdir "$G/functions/acm.usb0" "$G/functions/ecm.usb0" "$G/functions/mass_storage.usb0" 2>/dev/null || true
	rmdir "$G/configs/c.1/strings/0x409" "$G/configs/c.1" "$G/strings/0x409" "$G" 2>/dev/null || true
}

case "$1" in
	start)
		start_gadget
		;;
	stop)
		stop_gadget
		;;
	restart|reload)
		stop_gadget
		start_gadget
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
